---
version: "2.4"
services:
  app:
    image: nicholaswilde/babybuddy:latest
    container_name: babybuddyapp   # Container_name is an optional value for single-container
    # deployments to set a friendly container name.
    # Disable in swarm or other multi-container setups.
    # See README.md#configuration for other environment configuration options.
    environment:
      - ALLOWED_HOSTS=*           # comma separated list of IP addresses or hosts that can access the web UI
      - DJANGO_SETTINGS_MODULE=babybuddy.settings.base
      - SECRET_KEY="password"     # Generate a random string here to secure the Django instance
      - TIME_ZONE=                # In the tzdata format, IE, "America/Denver"
      - DEBUG=False               # Turn to False in production
    volumes:
      - ./data:/app/data:rw
      - media:/app/media:rw
    ports:
      - "8000:8000"               # For Portainer, select another port for babybuddy such as 7000, for example "7000:8000"
    restart: unless-stopped
volumes:
  data:
  media:
